use serde::{Deserialize, Serialize};

#[derive(Serialize)]
pub struct ConfigPayload {
    pub path: String,
    pub entries: Vec<ConfigEntry>,
}

#[derive(Serialize)]
pub struct ConfigEntry {
    pub key: String,
    pub value: String,
}

#[derive(Deserialize)]
pub struct ConfigUpdate {
    pub key: String,
    pub value: String,
}

#[tauri::command]
pub fn get_config() -> ConfigPayload {
    let path = config_file_path();
    let path_str = path.to_string_lossy().to_string();
    let contents = std::fs::read_to_string(&path).unwrap_or_default();
    let mut entries = Vec::new();
    for line in contents.lines() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        if let Some((key, value)) = line.split_once('=') {
            entries.push(ConfigEntry {
                key: key.trim().to_string(),
                value: value.trim().to_string(),
            });
        }
    }
    ConfigPayload {
        path: path_str,
        entries,
    }
}

#[tauri::command]
pub fn set_config(updates: Vec<ConfigUpdate>) -> Result<(), String> {
    let path = config_file_path();
    // Distinguish "file absent" (fine, start from empty) from "file exists but
    // is unreadable" (bad permissions, non-UTF-8). Treating an unreadable file
    // as empty and writing back only this call's keys would erase every other
    // setting, comment, and blank line - a single slider save wiping the file.
    let contents = match std::fs::read_to_string(&path) {
        Ok(contents) => contents,
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => String::new(),
        Err(e) => return Err(format!("Refusing to overwrite an unreadable config: {e}")),
    };
    let mut lines: Vec<String> = contents.lines().map(|l| l.to_string()).collect();

    for update in &updates {
        let new_line = format!("{}={}", update.key, update.value);
        let mut found = false;
        for line in &mut lines {
            let trimmed = line.trim();
            if !trimmed.starts_with('#')
                && let Some((k, _)) = trimmed.split_once('=')
                && k.trim() == update.key
            {
                *line = new_line.clone();
                found = true;
                break;
            }
        }
        if !found {
            lines.push(new_line);
        }
    }

    let mut output = lines.join("\n");
    if !output.ends_with('\n') {
        output.push('\n');
    }
    std::fs::write(&path, output).map_err(|e| format!("Failed to write config: {e}"))
}

#[tauri::command]
pub fn reset_config() -> Result<(), String> {
    let path = config_file_path();
    std::fs::write(&path, default_config_contents())
        .map_err(|e| format!("Failed to reset config: {e}"))
}

/// The template Reset writes. Only keys the app reads off the file are seeded:
/// the cosmetic `ui_*` slider values are deliberately left out because the
/// settings UI falls back to its own defaults for any absent key, so listing
/// them here would be a second set of defaults to keep in sync. Linux-only
/// keys are `#[cfg]`-gated so a Windows reset does not carry inert entries.
fn default_config_contents() -> String {
    let mut out = String::from(
        "# look configuration\n\
         # Generated by Look. Edit values below, then press Save Config to apply.\n\
         \n\
         # Indexing\n\
         file_scan_roots=Desktop,Documents,Downloads,Pictures,Videos\n\
         file_scan_extra_roots=\n\
         file_scan_depth=4\n\
         file_scan_limit=8000\n\
         file_exclude_paths=\n\
         ignored_patterns_sample=\n\
         # File ignore patterns. Format: ignored_patterns_<group>=Pattern1|Pattern2|Pattern3\n\
         # ignored_patterns_browser=~/AppData/Local/BraveSoftware/**/*.log|~/AppData/Local/Google/Chrome/**/*.tmp\n\
         # ignored_patterns_sqlite=~/Documents/git/project/**/*.db-wal|~/Documents/git/project/**/*.db-shm\n\
         lazy_indexing_enabled=true\n\
         skip_dir_names=node_modules,target,build,dist,.git,vendor,out,coverage,tmp,cache,venv\n\
         \n",
    );

    // WebKitGTK ghost-rendering workarounds only exist on the Linux webview;
    // the keys are inert on Windows, so don't seed them there.
    #[cfg(target_os = "linux")]
    out.push_str(
        "# Arch (and other affected stacks) - workarounds for WebKitGTK ghost rendering.\n\
         # arch_disable_gpu forces HardwareAccelerationPolicy::Never (needs restart);\n\
         # arch_disable_blur drops backdrop-filter for an opaque tint. Both default off;\n\
         # flip if you see slider trails or overlapping popovers.\n\
         arch_disable_gpu=false\n\
         arch_disable_blur=false\n\
         \n",
    );

    out.push_str(
        "# Running apps switcher: none, right\n\
         running_apps_placement=right\n\
         \n\
         # Clipboard history size (10-100). Out-of-range values fall back to 10.\n\
         clipboard_history_limit=10\n\
         \n\
         # Home-screen inner gap in px (0-24). 0 keeps the classic framed panel;\n\
         # above 0 the home screen splits into floating tiles separated by this gap.\n\
         inner_gap=0\n\
         \n\
         # Web answers - inline answer card for question-like queries. Set false to\n\
         # disable all network answer features and run fully offline.\n\
         ai_enabled=true\n\
         \n\
         # UI theme (empty = built-in default; pick one in Settings)\n\
         ui_theme=\n",
    );

    out
}

pub const ENV_CONFIG_PATH: &str = "LOOK_CONFIG_PATH";
const CONFIG_FILE: &str = ".look.config";

const CLIPBOARD_HISTORY_LIMIT_KEY: &str = "clipboard_history_limit";
pub const CLIPBOARD_HISTORY_LIMIT_DEFAULT: usize = 10;
pub const CLIPBOARD_HISTORY_LIMIT_MIN: usize = 10;
pub const CLIPBOARD_HISTORY_LIMIT_MAX: usize = 100;

/// Drops a trailing comment. `#` only starts one at the beginning of the line or after
/// whitespace, so it survives inside a value: cutting at the first `#` anywhere would
/// truncate a path like `/Users/me/pic#1.png` down to `/Users/me/pic`, silently
/// corrupting the setting. Must stay in step with the cross-platform reader
/// in `core/engine/src/config.rs` (`strip_comments`), since both parse the same file.
fn strip_inline_comment(value: &str) -> &str {
    let mut previous_is_whitespace = true;
    for (index, character) in value.char_indices() {
        if character == '#' && previous_is_whitespace {
            return &value[..index];
        }
        previous_is_whitespace = character.is_whitespace();
    }
    value
}

/// How many clipboard clips to keep, read from `clipboard_history_limit` in the
/// config file. Returns the default (10) when the key is absent, unparseable, or
/// outside the accepted [10, 100] range.
pub fn clipboard_history_limit() -> usize {
    let path = config_file_path();
    let Ok(contents) = std::fs::read_to_string(&path) else {
        return CLIPBOARD_HISTORY_LIMIT_DEFAULT;
    };
    parse_clipboard_history_limit(&contents)
}

/// Parses `clipboard_history_limit` out of raw config file contents. Split from
/// `clipboard_history_limit` so the parsing rules can be unit-tested without touching
/// the filesystem or the shared `LOOK_CONFIG_PATH` env var. The last assignment wins
/// (matching how the file is applied line by line); returns the default when the key is
/// absent, unparseable, or outside [10, 100].
fn parse_clipboard_history_limit(contents: &str) -> usize {
    let mut last_value: Option<&str> = None;
    for raw_line in contents.lines() {
        let line = strip_inline_comment(raw_line).trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        if let Some((key, value)) = line.split_once('=')
            && key.trim() == CLIPBOARD_HISTORY_LIMIT_KEY
        {
            last_value = Some(value.trim());
        }
    }
    if let Some(value) = last_value {
        match value.parse::<usize>() {
            Ok(parsed)
                if (CLIPBOARD_HISTORY_LIMIT_MIN..=CLIPBOARD_HISTORY_LIMIT_MAX)
                    .contains(&parsed) =>
            {
                return parsed;
            }
            _ => {}
        }
    }
    CLIPBOARD_HISTORY_LIMIT_DEFAULT
}

pub fn config_file_path() -> std::path::PathBuf {
    if let Ok(custom) = std::env::var(ENV_CONFIG_PATH) {
        let trimmed = custom.trim();
        if !trimmed.is_empty() {
            return std::path::PathBuf::from(trimmed);
        }
    }
    let home = std::env::var("HOME")
        .or_else(|_| std::env::var("USERPROFILE"))
        .unwrap_or_else(|_| ".".to_string());
    std::path::PathBuf::from(home).join(CONFIG_FILE)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn missing_key_falls_back_to_default() {
        assert_eq!(
            parse_clipboard_history_limit(""),
            CLIPBOARD_HISTORY_LIMIT_DEFAULT
        );
        assert_eq!(
            parse_clipboard_history_limit("file_scan_limit=8000\nai_enabled=true\n"),
            CLIPBOARD_HISTORY_LIMIT_DEFAULT
        );
    }

    #[test]
    fn valid_in_range_value_is_used() {
        assert_eq!(
            parse_clipboard_history_limit("clipboard_history_limit=50\n"),
            50
        );
    }

    #[test]
    fn boundary_values_are_accepted() {
        assert_eq!(
            parse_clipboard_history_limit("clipboard_history_limit=10\n"),
            10
        );
        assert_eq!(
            parse_clipboard_history_limit("clipboard_history_limit=100\n"),
            100
        );
    }

    #[test]
    fn out_of_range_values_fall_back_to_default() {
        // Below min, above max, and zero all revert to the default rather than clamp.
        assert_eq!(
            parse_clipboard_history_limit("clipboard_history_limit=9\n"),
            CLIPBOARD_HISTORY_LIMIT_DEFAULT
        );
        assert_eq!(
            parse_clipboard_history_limit("clipboard_history_limit=101\n"),
            CLIPBOARD_HISTORY_LIMIT_DEFAULT
        );
        assert_eq!(
            parse_clipboard_history_limit("clipboard_history_limit=0\n"),
            CLIPBOARD_HISTORY_LIMIT_DEFAULT
        );
    }

    #[test]
    fn non_numeric_and_negative_values_fall_back_to_default() {
        assert_eq!(
            parse_clipboard_history_limit("clipboard_history_limit=abc\n"),
            CLIPBOARD_HISTORY_LIMIT_DEFAULT
        );
        // `-5` is not a valid usize, so parsing fails and we fall back.
        assert_eq!(
            parse_clipboard_history_limit("clipboard_history_limit=-5\n"),
            CLIPBOARD_HISTORY_LIMIT_DEFAULT
        );
        assert_eq!(
            parse_clipboard_history_limit("clipboard_history_limit=\n"),
            CLIPBOARD_HISTORY_LIMIT_DEFAULT
        );
    }

    #[test]
    fn surrounding_whitespace_is_ignored() {
        assert_eq!(
            parse_clipboard_history_limit("  clipboard_history_limit = 42 \n"),
            42
        );
    }

    #[test]
    fn trailing_inline_comment_is_stripped() {
        assert_eq!(
            parse_clipboard_history_limit(
                "clipboard_history_limit=50   # bumped for my workflow\n"
            ),
            50
        );
        // The comment must not smuggle an out-of-range value past the range check.
        assert_eq!(
            parse_clipboard_history_limit("clipboard_history_limit=999 # too big\n"),
            CLIPBOARD_HISTORY_LIMIT_DEFAULT
        );
    }

    #[test]
    fn commented_out_line_is_not_read() {
        assert_eq!(
            parse_clipboard_history_limit("# clipboard_history_limit=50\n"),
            CLIPBOARD_HISTORY_LIMIT_DEFAULT
        );
    }

    #[test]
    fn key_must_match_exactly_not_as_a_suffix() {
        // A different key that merely ends with the name must not match.
        assert_eq!(
            parse_clipboard_history_limit("my_clipboard_history_limit=50\n"),
            CLIPBOARD_HISTORY_LIMIT_DEFAULT
        );
    }

    #[test]
    fn last_assignment_wins() {
        assert_eq!(
            parse_clipboard_history_limit(
                "clipboard_history_limit=20\nclipboard_history_limit=80\n"
            ),
            80
        );
        // When the last duplicate is invalid the whole lookup falls back to the default,
        // even though an earlier line held a valid value.
        assert_eq!(
            parse_clipboard_history_limit(
                "clipboard_history_limit=50\nclipboard_history_limit=oops\n"
            ),
            CLIPBOARD_HISTORY_LIMIT_DEFAULT
        );
    }
}
