use serde::{Deserialize, Serialize};

#[derive(Serialize)]
pub struct ConfigPayload {
    pub path: String,
    pub entries: Vec<ConfigEntry>,
}

#[derive(Serialize)]
pub struct ConfigEntry {
    pub key: String,
    pub value: String,
}

#[derive(Deserialize)]
pub struct ConfigUpdate {
    pub key: String,
    pub value: String,
}

#[tauri::command]
pub fn get_config() -> ConfigPayload {
    let path = config_file_path();
    let path_str = path.to_string_lossy().to_string();
    let contents = std::fs::read_to_string(&path).unwrap_or_default();
    let mut entries = Vec::new();
    for line in contents.lines() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        if let Some((key, value)) = line.split_once('=') {
            entries.push(ConfigEntry {
                key: key.trim().to_string(),
                value: value.trim().to_string(),
            });
        }
    }
    ConfigPayload {
        path: path_str,
        entries,
    }
}

#[tauri::command]
pub fn set_config(updates: Vec<ConfigUpdate>) -> Result<(), String> {
    let path = config_file_path();
    // Distinguish "file absent" (fine, start from empty) from "file exists but
    // is unreadable" (bad permissions, non-UTF-8). Treating an unreadable file
    // as empty and writing back only this call's keys would erase every other
    // setting, comment, and blank line - a single slider save wiping the file.
    let contents = match std::fs::read_to_string(&path) {
        Ok(contents) => contents,
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => String::new(),
        Err(e) => return Err(format!("Refusing to overwrite an unreadable config: {e}")),
    };
    let mut lines: Vec<String> = contents.lines().map(|l| l.to_string()).collect();

    for update in &updates {
        let new_line = format!("{}={}", update.key, update.value);
        let mut found = false;
        for line in &mut lines {
            let trimmed = line.trim();
            if !trimmed.starts_with('#')
                && let Some((k, _)) = trimmed.split_once('=')
                && k.trim() == update.key
            {
                *line = new_line.clone();
                found = true;
                break;
            }
        }
        if !found {
            lines.push(new_line);
        }
    }

    let mut output = lines.join("\n");
    if !output.ends_with('\n') {
        output.push('\n');
    }
    std::fs::write(&path, output).map_err(|e| format!("Failed to write config: {e}"))
}

#[tauri::command]
pub fn reset_config() -> Result<(), String> {
    let path = config_file_path();
    std::fs::write(&path, default_config_contents())
        .map_err(|e| format!("Failed to reset config: {e}"))
}

/// The template Reset writes. Only keys the app reads off the file are seeded:
/// the cosmetic `ui_*` slider values are deliberately left out because the
/// settings UI falls back to its own defaults for any absent key, so listing
/// them here would be a second set of defaults to keep in sync. Linux-only
/// keys are `#[cfg]`-gated so a Windows reset does not carry inert entries.
fn default_config_contents() -> String {
    let mut out = String::from(
        "# look configuration\n\
         # Generated by Look. Edit values below, then press Save Config to apply.\n\
         \n\
         # Indexing\n\
         file_scan_roots=Desktop,Documents,Downloads,Pictures,Videos\n\
         file_scan_extra_roots=\n\
         file_scan_depth=4\n\
         file_scan_limit=8000\n\
         file_exclude_paths=\n\
         lazy_indexing_enabled=true\n\
         skip_dir_names=node_modules,target,build,dist,.git,vendor,out,coverage,tmp,cache,venv\n\
         \n",
    );

    // WebKitGTK ghost-rendering workarounds only exist on the Linux webview;
    // the keys are inert on Windows, so don't seed them there.
    #[cfg(target_os = "linux")]
    out.push_str(
        "# Arch (and other affected stacks) - workarounds for WebKitGTK ghost rendering.\n\
         # arch_disable_gpu forces HardwareAccelerationPolicy::Never (needs restart);\n\
         # arch_disable_blur drops backdrop-filter for an opaque tint. Both default off;\n\
         # flip if you see slider trails or overlapping popovers.\n\
         arch_disable_gpu=false\n\
         arch_disable_blur=false\n\
         \n",
    );

    out.push_str(
        "# Running apps switcher: none, right\n\
         running_apps_placement=right\n\
         \n\
         # Home-screen inner gap in px (0-24). 0 keeps the classic framed panel;\n\
         # above 0 the home screen splits into floating tiles separated by this gap.\n\
         inner_gap=0\n\
         \n\
         # Web answers - inline answer card for question-like queries. Set false to\n\
         # disable all network answer features and run fully offline.\n\
         ai_enabled=true\n\
         \n\
         # UI theme (empty = built-in default; pick one in Settings)\n\
         ui_theme=\n",
    );

    out
}

pub const ENV_CONFIG_PATH: &str = "LOOK_CONFIG_PATH";
const CONFIG_FILE: &str = ".look.config";

pub fn config_file_path() -> std::path::PathBuf {
    if let Ok(custom) = std::env::var(ENV_CONFIG_PATH) {
        let trimmed = custom.trim();
        if !trimmed.is_empty() {
            return std::path::PathBuf::from(trimmed);
        }
    }
    let home = std::env::var("HOME")
        .or_else(|_| std::env::var("USERPROFILE"))
        .unwrap_or_else(|_| ".".to_string());
    std::path::PathBuf::from(home).join(CONFIG_FILE)
}
