/// Language detection and keyword/comment definitions.
/// Ported from macOS `SyntaxHighlighter.swift` - same extensions, same keywords.

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Language {
    C,
    Cpp,
    Css,
    Go,
    Html,
    Java,
    JavaScript,
    Json,
    Markdown,
    Python,
    Ruby,
    Rust,
    Shell,
    Swift,
    TypeScript,
    Yaml,
    Zig,
    Plain,
}

impl Language {
    pub fn from_path(path: &str) -> Self {
        let ext = path.rsplit('.').next().unwrap_or("").to_ascii_lowercase();
        match ext.as_str() {
            "go" => Self::Go,
            "swift" => Self::Swift,
            "rs" => Self::Rust,
            "py" => Self::Python,
            "rb" => Self::Ruby,
            "js" | "mjs" | "cjs" | "jsx" => Self::JavaScript,
            "ts" | "tsx" => Self::TypeScript,
            "c" | "h" | "m" => Self::C,
            "cpp" | "cc" | "cxx" | "hpp" | "hh" | "hxx" | "mm" => Self::Cpp,
            "java" | "kt" | "kts" | "scala" | "groovy" => Self::Java,
            "zig" => Self::Zig,
            "sh" | "bash" | "zsh" | "fish" => Self::Shell,
            "html" | "htm" | "xml" | "svg" | "vue" | "svelte" => Self::Html,
            "css" | "scss" | "sass" | "less" => Self::Css,
            "json" => Self::Json,
            "yaml" | "yml" | "toml" => Self::Yaml,
            "md" | "markdown" | "rst" => Self::Markdown,
            _ => Self::Plain,
        }
    }

    pub fn keywords(self) -> &'static [&'static str] {
        match self {
            Self::Go => &[
                "break",
                "case",
                "chan",
                "const",
                "continue",
                "default",
                "defer",
                "else",
                "fallthrough",
                "for",
                "func",
                "go",
                "goto",
                "if",
                "import",
                "interface",
                "map",
                "package",
                "range",
                "return",
                "select",
                "struct",
                "switch",
                "type",
                "var",
                "nil",
                "true",
                "false",
                "iota",
            ],
            Self::Swift => &[
                "associatedtype",
                "class",
                "deinit",
                "enum",
                "extension",
                "fileprivate",
                "func",
                "import",
                "init",
                "inout",
                "internal",
                "let",
                "open",
                "operator",
                "private",
                "protocol",
                "public",
                "static",
                "struct",
                "subscript",
                "typealias",
                "var",
                "break",
                "case",
                "continue",
                "default",
                "defer",
                "do",
                "else",
                "fallthrough",
                "for",
                "guard",
                "if",
                "in",
                "repeat",
                "return",
                "switch",
                "where",
                "while",
                "as",
                "Any",
                "catch",
                "false",
                "is",
                "nil",
                "rethrows",
                "self",
                "Self",
                "super",
                "throw",
                "throws",
                "true",
                "try",
                "async",
                "await",
                "actor",
            ],
            Self::Rust => &[
                "as", "async", "await", "break", "const", "continue", "crate", "dyn", "else",
                "enum", "extern", "false", "fn", "for", "if", "impl", "in", "let", "loop", "match",
                "mod", "move", "mut", "pub", "ref", "return", "self", "Self", "static", "struct",
                "super", "trait", "true", "type", "unsafe", "use", "where", "while",
            ],
            Self::Python => &[
                "False", "None", "True", "and", "as", "assert", "async", "await", "break", "class",
                "continue", "def", "del", "elif", "else", "except", "finally", "for", "from",
                "global", "if", "import", "in", "is", "lambda", "nonlocal", "not", "or", "pass",
                "raise", "return", "try", "while", "with", "yield",
            ],
            Self::JavaScript | Self::TypeScript => &[
                "var",
                "let",
                "const",
                "function",
                "return",
                "if",
                "else",
                "for",
                "while",
                "do",
                "switch",
                "case",
                "default",
                "break",
                "continue",
                "new",
                "this",
                "super",
                "class",
                "extends",
                "import",
                "export",
                "from",
                "async",
                "await",
                "yield",
                "typeof",
                "instanceof",
                "in",
                "of",
                "try",
                "catch",
                "finally",
                "throw",
                "true",
                "false",
                "null",
                "undefined",
                "void",
                "delete",
                "interface",
                "type",
                "enum",
                "public",
                "private",
                "protected",
                "readonly",
            ],
            Self::C => &[
                "auto", "break", "case", "char", "const", "continue", "default", "do", "double",
                "else", "enum", "extern", "float", "for", "goto", "if", "inline", "int", "long",
                "register", "restrict", "return", "short", "signed", "sizeof", "static", "struct",
                "switch", "typedef", "union", "unsigned", "void", "volatile", "while",
            ],
            Self::Cpp => &[
                "alignas",
                "alignof",
                "auto",
                "bool",
                "break",
                "case",
                "catch",
                "char",
                "class",
                "const",
                "constexpr",
                "continue",
                "decltype",
                "default",
                "delete",
                "do",
                "double",
                "else",
                "enum",
                "explicit",
                "export",
                "extern",
                "false",
                "float",
                "for",
                "friend",
                "goto",
                "if",
                "inline",
                "int",
                "long",
                "mutable",
                "namespace",
                "new",
                "noexcept",
                "nullptr",
                "operator",
                "private",
                "protected",
                "public",
                "return",
                "short",
                "signed",
                "sizeof",
                "static",
                "static_cast",
                "struct",
                "switch",
                "template",
                "this",
                "throw",
                "true",
                "try",
                "typedef",
                "typeid",
                "typename",
                "union",
                "unsigned",
                "using",
                "virtual",
                "void",
                "volatile",
                "while",
            ],
            Self::Java => &[
                "abstract",
                "assert",
                "boolean",
                "break",
                "byte",
                "case",
                "catch",
                "char",
                "class",
                "const",
                "continue",
                "default",
                "do",
                "double",
                "else",
                "enum",
                "extends",
                "false",
                "final",
                "finally",
                "float",
                "for",
                "goto",
                "if",
                "implements",
                "import",
                "instanceof",
                "int",
                "interface",
                "long",
                "native",
                "new",
                "null",
                "package",
                "private",
                "protected",
                "public",
                "return",
                "short",
                "static",
                "strictfp",
                "super",
                "switch",
                "synchronized",
                "this",
                "throw",
                "throws",
                "transient",
                "true",
                "try",
                "void",
                "volatile",
                "while",
                "fun",
                "val",
                "var",
            ],
            Self::Ruby => &[
                "alias", "and", "begin", "break", "case", "class", "def", "do", "else", "elsif",
                "end", "ensure", "false", "for", "if", "in", "module", "next", "nil", "not", "or",
                "redo", "rescue", "retry", "return", "self", "super", "then", "true", "undef",
                "unless", "until", "when", "while", "yield",
            ],
            Self::Shell => &[
                "if", "then", "else", "elif", "fi", "case", "esac", "for", "while", "do", "done",
                "in", "function", "return", "local", "export", "unset", "readonly", "declare",
                "let", "alias", "source",
            ],
            Self::Zig => &[
                "addrspace",
                "align",
                "allowzero",
                "and",
                "anyframe",
                "anytype",
                "asm",
                "async",
                "await",
                "break",
                "callconv",
                "catch",
                "comptime",
                "const",
                "continue",
                "defer",
                "else",
                "enum",
                "errdefer",
                "error",
                "export",
                "extern",
                "fn",
                "for",
                "if",
                "inline",
                "noalias",
                "nosuspend",
                "opaque",
                "or",
                "orelse",
                "packed",
                "pub",
                "resume",
                "return",
                "struct",
                "suspend",
                "switch",
                "test",
                "threadlocal",
                "try",
                "union",
                "unreachable",
                "undefined",
                "var",
                "volatile",
                "while",
                "true",
                "false",
                "null",
            ],
            Self::Json | Self::Yaml => &["true", "false", "null"],
            _ => &[],
        }
    }

    /// Returns (line_comment_prefix, block_comment_delimiters).
    pub fn comment_delimiters(
        self,
    ) -> (Option<&'static str>, Option<(&'static str, &'static str)>) {
        match self {
            Self::Python | Self::Ruby | Self::Shell | Self::Yaml => (Some("#"), None),
            Self::Html => (None, Some(("<!--", "-->"))),
            Self::Css => (None, Some(("/*", "*/"))),
            Self::Json | Self::Markdown | Self::Plain => (None, None),
            Self::Zig => (Some("//"), None),
            _ => (Some("//"), Some(("/*", "*/"))),
        }
    }
}
