//! Auto-install and communicate with the Look GNOME Shell extension.
//!
//! The extension exposes a single D-Bus method `FocusApp(desktop_id)` that
//! uses gnome-shell's internal `Shell.App.activate()` to focus existing
//! windows - the same mechanism GNOME's own Activities search uses.

use std::path::PathBuf;

use super::dbus::{runtime as dbus_runtime, session as dbus_conn};

const EXT_UUID: &str = "look-integration@lookapp";
const DBUS_NAME: &str = "com.look.ShellIntegration";
const DBUS_PATH: &str = "/com/look/ShellIntegration";
const DBUS_IFACE: &str = "com.look.ShellIntegration";

// metadata.json is generated by build.rs with `version` derived from the app
// version in tauri.conf.json - every Look release auto-bumps the extension
// version, so the developer never has to edit metadata by hand.
const METADATA_JSON: &str = include_str!(concat!(env!("OUT_DIR"), "/gnome-ext-metadata.json"));
const EXTENSION_JS: &str = include_str!("../../gnome-shell-extension/extension.js");

/// Install the GNOME Shell extension if not already present, then enable it.
pub fn ensure_installed() {
    let ext_dir = extension_dir();
    let metadata_path = ext_dir.join("metadata.json");
    let extension_path = ext_dir.join("extension.js");

    // Check if already installed with current version
    let needs_install = if metadata_path.exists() && extension_path.exists() {
        let existing_ext = std::fs::read_to_string(&extension_path).unwrap_or_default();
        let existing_meta = std::fs::read_to_string(&metadata_path).unwrap_or_default();
        existing_ext != EXTENSION_JS || existing_meta != METADATA_JSON
    } else {
        true
    };

    if needs_install {
        // Use `gnome-extensions install` with a zip so GNOME Shell picks up
        // the extension immediately - no re-login required on Wayland.
        if install_via_gnome_extensions() {
            eprintln!("[look] Installed GNOME Shell extension via gnome-extensions install");
            enable_extension();
            return;
        }

        // Fallback: write files manually (needs re-login on Wayland)
        if let Err(e) = std::fs::create_dir_all(&ext_dir) {
            eprintln!("[look] Failed to create extension dir: {e}");
            return;
        }
        if let Err(e) = std::fs::write(&metadata_path, METADATA_JSON) {
            eprintln!("[look] Failed to write metadata.json: {e}");
            return;
        }
        if let Err(e) = std::fs::write(&extension_path, EXTENSION_JS) {
            eprintln!("[look] Failed to write extension.js: {e}");
            return;
        }
        eprintln!("[look] Installed GNOME Shell extension: {EXT_UUID} (manual, needs re-login)");
        enable_extension();
    }
}

/// Build a zip of the extension in /tmp and install via `gnome-extensions install --force`.
fn install_via_gnome_extensions() -> bool {
    let zip_path = std::env::temp_dir().join("look-gnome-ext.zip");
    if let Err(e) = build_extension_zip(&zip_path) {
        eprintln!("[look] Failed to create extension zip: {e}");
        return false;
    }
    let result = super::host_command("gnome-extensions")
        .args(["install", "--force"])
        .arg(&zip_path)
        .output();
    let _ = std::fs::remove_file(&zip_path);
    match result {
        Ok(output) if output.status.success() => true,
        Ok(output) => {
            let stderr = String::from_utf8_lossy(&output.stderr);
            eprintln!("[look] gnome-extensions install failed: {stderr}");
            false
        }
        Err(e) => {
            eprintln!("[look] gnome-extensions not found: {e}");
            false
        }
    }
}

fn build_extension_zip(path: &std::path::Path) -> std::io::Result<()> {
    use std::io::Write;

    let file = std::fs::File::create(path)?;
    let mut zip = zip::ZipWriter::new(file);
    let options = zip::write::SimpleFileOptions::default()
        .compression_method(zip::CompressionMethod::Deflated);

    zip.start_file("metadata.json", options)?;
    zip.write_all(METADATA_JSON.as_bytes())?;

    zip.start_file("extension.js", options)?;
    zip.write_all(EXTENSION_JS.as_bytes())?;

    zip.finish()?;
    Ok(())
}

/// Get the cursor position via the GNOME Shell extension's GetPointer D-Bus method.
/// Works on Wayland where Tauri's cursor_position() is unavailable.
pub fn get_pointer() -> Option<(i32, i32)> {
    let conn = dbus_conn()?;
    dbus_runtime().block_on(async {
        let reply: (i32, i32) = conn
            .call_method(
                Some(DBUS_NAME),
                DBUS_PATH,
                Some(DBUS_IFACE),
                "GetPointer",
                &(),
            )
            .await
            .ok()?
            .body()
            .deserialize()
            .ok()?;
        Some(reply)
    })
}

/// Classification of a D-Bus error against the Look extension. Extracted from
/// the call sites so it can be unit-tested without a live D-Bus session.
#[derive(Debug, PartialEq, Eq)]
enum ExtensionError {
    /// Extension is loaded but missing the method we called - almost always
    /// the "GNOME Shell has stale JS in memory" case, since the on-disk
    /// extension always defines every method `gnome_ext.rs` calls.
    Stale,
    /// Extension D-Bus service isn't owned by anyone (not installed/enabled).
    NotRunning,
    /// Any other failure (timeout, malformed reply, bus error).
    Other,
}

fn classify_dbus_error(err: &zbus::Error) -> ExtensionError {
    if let zbus::Error::MethodError(name, _, _) = err {
        match name.as_str() {
            "org.freedesktop.DBus.Error.UnknownMethod" => return ExtensionError::Stale,
            "org.freedesktop.DBus.Error.ServiceUnknown"
            | "org.freedesktop.DBus.Error.NameHasNoOwner" => return ExtensionError::NotRunning,
            _ => {}
        }
    }
    ExtensionError::Other
}

/// List desktop IDs of apps that GNOME Shell considers "running" (i.e. have
/// at least one window). Returns None if the extension isn't reachable -
/// callers should fall back to other heuristics in that case. Returns
/// `Some(vec![])` if the extension answered but no apps have windows.
pub fn list_windowed_apps() -> Option<Vec<String>> {
    let conn = dbus_conn()?;
    dbus_runtime().block_on(async {
        match conn
            .call_method(
                Some(DBUS_NAME),
                DBUS_PATH,
                Some(DBUS_IFACE),
                "ListWindowedApps",
                &(),
            )
            .await
        {
            Ok(reply) => reply
                .body()
                .deserialize::<(Vec<String>,)>()
                .ok()
                .map(|r| r.0),
            Err(err) => {
                if classify_dbus_error(&err) == ExtensionError::Stale {
                    warn_stale_extension_once();
                }
                None
            }
        }
    })
}

fn warn_stale_extension_once() {
    static WARNED: std::sync::OnceLock<()> = std::sync::OnceLock::new();
    WARNED.get_or_init(|| {
        eprintln!(
            "[look] GNOME Shell has an outdated Look extension loaded in memory \
             (missing ListWindowedApps). Log out and back in to refresh - \
             gnome-shell can't hot-reload extension JS on Wayland."
        );
    });
}

/// Try to focus an app by its desktop file ID using the GNOME Shell extension.
/// Returns true if the app was focused (had existing windows).
///
/// Uses zbus to call directly from Look's process (which has focus),
/// so GNOME trusts the activation request without showing a "ready" popup.
pub fn try_focus_app(desktop_id: &str) -> bool {
    let Some(conn) = dbus_conn() else {
        return false;
    };
    let id = desktop_id.to_string();
    dbus_runtime()
        .block_on(async {
            let reply: (bool,) = conn
                .call_method(
                    Some(DBUS_NAME),
                    DBUS_PATH,
                    Some(DBUS_IFACE),
                    "FocusApp",
                    &id,
                )
                .await
                .ok()?
                .body()
                .deserialize()
                .ok()?;
            Some(reply.0)
        })
        .unwrap_or(false)
}

fn extension_dir() -> PathBuf {
    dirs::data_dir()
        .unwrap_or_else(|| PathBuf::from("~/.local/share"))
        .join("gnome-shell/extensions")
        .join(EXT_UUID)
}

fn enable_extension() {
    // Use gnome-extensions CLI which properly handles enabled/disabled state.
    // Raw gsettings manipulation misses the disabled-extensions list and
    // other state that GNOME tracks internally.
    let result = super::host_command("gnome-extensions")
        .args(["enable", EXT_UUID])
        .output();

    match &result {
        Ok(output) if output.status.success() => {
            eprintln!("[look] Enabled extension via gnome-extensions CLI");
        }
        _ => {
            // Fallback: raw gsettings for older GNOME or minimal installs
            let output = super::host_command("gsettings")
                .args(["get", "org.gnome.shell", "enabled-extensions"])
                .output();

            let current = output
                .ok()
                .and_then(|o| String::from_utf8(o.stdout).ok())
                .unwrap_or_default();
            let current = current.trim();

            if current.contains(EXT_UUID) {
                return;
            }

            let mut extensions: Vec<String> = if current == "@as []" || current == "[]" {
                Vec::new()
            } else {
                current
                    .trim_start_matches('[')
                    .trim_end_matches(']')
                    .split(',')
                    .map(|s| s.trim().trim_matches('\'').trim_matches('"').to_string())
                    .filter(|s| !s.is_empty())
                    .collect()
            };

            extensions.push(EXT_UUID.to_string());

            let new_value = format!(
                "[{}]",
                extensions
                    .iter()
                    .map(|e| format!("'{e}'"))
                    .collect::<Vec<_>>()
                    .join(", ")
            );

            let _ = super::host_command("gsettings")
                .args(["set", "org.gnome.shell", "enabled-extensions", &new_value])
                .output();
        }
    }
}

#[cfg(test)]
mod tests {
    //! Regression tests for the extension-update path.
    //!
    //! Why: GNOME Shell on Wayland can't hot-reload extension JS. When we ship
    //! a new Look that changes `extension.js`, users get the new file on disk
    //! but the live shell keeps the old code in memory until they log out.
    //! Without a `version` bump in `metadata.json`, users have no upgrade
    //! signal at all - silent breakage. These tests force every extension.js
    //! change to be paired with a version bump (via `.lock`), and verify the
    //! Rust↔JS D-Bus contract stays in sync.

    use super::*;

    const LOCK: &str = include_str!("../../gnome-shell-extension/.lock");

    /// Methods called from Rust must be declared in the extension's IFACE XML.
    /// Add to this list when adding a new D-Bus call site in this file.
    const RUST_CALLED_METHODS: &[&str] = &["FocusApp", "GetPointer", "ListWindowedApps"];

    fn fnv1a_hex(bytes: &[u8]) -> String {
        let mut h: u64 = 0xcbf29ce484222325;
        for b in bytes {
            h ^= *b as u64;
            h = h.wrapping_mul(0x100000001b3);
        }
        format!("{h:016x}")
    }

    fn parse_lock_field<'a>(lock: &'a str, key: &str) -> Option<&'a str> {
        lock.lines()
            .find_map(|l| l.strip_prefix(&format!("{key}=")))
            .map(str::trim)
    }

    fn parse_metadata_version(meta: &str) -> Option<u32> {
        // Tiny JSON-free parser: look for `"version": N` (number, not string).
        // metadata.json is small and hand-written; pulling in serde just for
        // this would be overkill.
        let needle = "\"version\"";
        let after = meta.split_once(needle)?.1;
        let after = after.trim_start().strip_prefix(':')?.trim_start();
        let digits: String = after.chars().take_while(|c| c.is_ascii_digit()).collect();
        digits.parse().ok()
    }

    #[test]
    fn metadata_has_integer_version_field() {
        let version = parse_metadata_version(METADATA_JSON).expect(
            "metadata.json must declare an integer `version` field - without it, \
             GNOME Shell has no way to detect that the extension was updated.",
        );
        assert!(version >= 1, "extension version must be >= 1");
    }

    #[test]
    fn iface_declares_every_method_called_from_rust() {
        // If Rust adds a new D-Bus call but the extension's IFACE XML doesn't
        // declare the method, every call will fail with UnknownMethod at
        // runtime. Catch the drift at compile/test time instead.
        for method in RUST_CALLED_METHODS {
            let needle = format!("<method name=\"{method}\">");
            assert!(
                EXTENSION_JS.contains(&needle),
                "extension.js IFACE XML must declare method `{method}` - it's \
                 called from gnome_ext.rs. If you removed it intentionally, \
                 update RUST_CALLED_METHODS in this test."
            );
        }
    }

    #[test]
    fn extension_js_content_matches_lock() {
        // metadata.json `version` is auto-derived from tauri.conf.json by
        // build.rs, so every Look release bumps it automatically - no manual
        // edit needed there.
        //
        // What this test still guards: silent edits to extension.js. The
        // lockfile pins the current hash; any change forces the developer to
        // (a) see the test fail, (b) consciously update the lock with the new
        // hash. That confirms the change was intentional and prevents
        // accidental drift sneaking past review.
        let locked_hash = parse_lock_field(LOCK, "extension_fnv1a")
            .expect(".lock must contain `extension_fnv1a=…`");
        let actual_hash = fnv1a_hex(EXTENSION_JS.as_bytes());
        assert_eq!(
            actual_hash, locked_hash,
            "extension.js content changed. If this was intentional, update \
             apps/linows/src-tauri/src/gnome-shell-extension/.lock to:\n  \
             extension_fnv1a={actual_hash}\n\
             (metadata.json `version` auto-bumps with the app version, so no \
             manual edit is needed there - but reviewing the JS diff is.)"
        );
    }

    #[test]
    fn classify_unknown_method_as_stale() {
        let err = zbus::Error::MethodError(
            zbus::names::OwnedErrorName::try_from("org.freedesktop.DBus.Error.UnknownMethod")
                .unwrap(),
            None,
            zbus::Message::method_call("/x", "x")
                .unwrap()
                .interface("x.x")
                .unwrap()
                .build(&())
                .unwrap(),
        );
        assert_eq!(classify_dbus_error(&err), ExtensionError::Stale);
    }

    #[test]
    fn classify_service_unknown_as_not_running() {
        let err = zbus::Error::MethodError(
            zbus::names::OwnedErrorName::try_from("org.freedesktop.DBus.Error.ServiceUnknown")
                .unwrap(),
            None,
            zbus::Message::method_call("/x", "x")
                .unwrap()
                .interface("x.x")
                .unwrap()
                .build(&())
                .unwrap(),
        );
        assert_eq!(classify_dbus_error(&err), ExtensionError::NotRunning);
    }

    #[test]
    fn classify_other_method_error_as_other() {
        let err = zbus::Error::MethodError(
            zbus::names::OwnedErrorName::try_from("org.example.SomeOtherError").unwrap(),
            None,
            zbus::Message::method_call("/x", "x")
                .unwrap()
                .interface("x.x")
                .unwrap()
                .build(&())
                .unwrap(),
        );
        assert_eq!(classify_dbus_error(&err), ExtensionError::Other);
    }
}
